language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install south
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - ./runtests.sh
env:
  - DJANGO=1.3.3
  - DJANGO=1.4.1
  - DJANGO=1.5
